### PR TITLE
GWTP-136 : Delete old dispatch RPC code

### PR DESCRIPTION
**Pull request by meriouma**

### CODE REVIEW

**Comment by christiangoudreau** [comment]
Isn't that breaking?

**Comment by meriouma** [comment]
Yes, for people still using the deprecated classes. They have been deprecated since GWTP 1.0

**Comment by christiangoudreau** [comment]
But shouldn't be removed from GWTP 2.0 rather than 1.5? I guess that it's my real fondamental question

**Comment by meriouma** [comment]
I believe our deprecation policy was to leave it deprecated for at least 2 minor versions before removing it, or 1 major version. I think it makes sense to drop it in 1.5

**Comment by christiangoudreau** [comment]
Sounds good then, lgtm

**Comment by Chris-V** [comment]
LGTM

**Pull request merged**
