### PR TITLE
update readme snapshot version, remove duplicate archetype link, remove ...

### PR DESCRIPTION
**Pull request by rdwallis**
...moving to github link & move plugins higher up

### CODE REVIEW

**Comment by rdwallis** [comment]
While archetypes are outdated, we should mention that in some way.  Otherwise it'll frustrate new users.  Maybe recommend new users start with the IntelliJ or Eclipse plugins instead.

**Comment by christiangoudreau** [comment]
Agreed, I'll bug @branflake2267  to update the archetypes :D

**Comment by Chris-V** [comment]
lgtm

**Comment by branflake2267** [comment]
The basic archetype has an issue, once the pom.xml is fixed, I can run the generator.

**Comment by rdwallis** [comment]
@branflake2267, what about making basic archetype the only archetype?  That'll make it a lot easier to maintain.

It'll probably also make things simpler for new users.  The current choices are a bit intimidating.

**Comment by christiangoudreau** [comment]
I agree with that. Well, at the very least we should officially support ourselves basic archetype while having all the other ones as extensions

**Comment by branflake2267** [comment]
I'll leave the removal decision up to you, I'm fine with however you'd like to run the show there. :)

**Comment by branflake2267** [comment]
Feel free to delete all the archetypes except basic. Sounds good.

**Comment by branflake2267** [comment]
Just have to fix the pom.xml configure so its legit, and were good to go.

**Pull request merged**
