### PR TITLE
Support regular expressions for PathParams

### PR DESCRIPTION
**Pull request by alexrashed**
Hi everyone :)

We discovered an unsupported feature of the JSR 311 in the gwt-dispatch-rest project.
According to the specification (section 3.4 - URI Templates) it is allowed to define regular expressions for the path parameters.
The consequence are errors during the path parameter substitution if such regular expressions are defined.
We implemented the extraction of the regular expressions during the compile / client stub generation (RestActionGenerator) as well as a runtime check of the parameter substitution against the regular expression (DefaultUriFactor - only if the client side logging is activated, otherwise the regex will be ignored).

### CODE REVIEW

**Comment by olafleur** [comment]
Thanks for the contribution! @Chris-V could you take a look whenever you got some time?

**Comment by christiangoudreau** [comment]
Awesome, thanks!

**Comment by Chris-V** [comment]
Sorry for the delay. I will review your changes this week. Thanks for the contribution!

**Comment by Chris-V** [comment]
Hi, I recently completed a rewrite of all code generators to Java's APT in gwtp/processors_migration. It's been in the work since July, hence the my delay in merging your PR. Going forward, this will be how we generate code in GWTP and will help us support GWT 3 when it comes out.

I'm going to merge your branch and keep the client code. Because the generators are no more, I will need to rewrite the generators part. I don't mind doing it, but if you prefer doing it yourself, feel free to chime in!

**Comment by alexrashed** [comment]
Thanks! But it would be great if you find the time to do so, I won't be able to participate in the next weeks / months.

**Comment by Chris-V** [comment]
This PR should have the same behavior under the new processors structure.

https://github.com/ArcBees/GWTP/pull/760

**Pull request closed without merging**
